name: Deploy to server
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: run deployment script over ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NATURE_MAP_SERVER_HOST }}
          username: ${{ secrets.NATURE_MAP_SERVER_USERNAME }}
          password: ${{ secrets.NATURE_MAP_SERVER_PASSWORD }}
          port: ${{ secrets.NATURE_MAP_SERVER_PORT }}
          script: /home/deploy.sh
